---
title: "TradingView In R Notebook"
output: html_notebook
---

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tradingview)
library(tidyverse)
library(tidyquant)
```

```{r}
data <- iris %>% mutate(
  time = Sys.time() + (row_number() * 60 * 60)
)
data
```

```{r}
aapl <- tq_get("AAPL") %>% mutate(time = date)
appl
```

## Render

~~Doubleclick on chart to interact (by default pointer events are disabled because it interferes with Rmd vertical scrolling in RStudio)~~ Will figure that out later.

```{r}
tradingview(data, list(
  chart = list(
    decimals = 2
  ),
  width = list(
    type = "line",
    width = 1,
    value = "Sepal.Width",
    color = "rgba(255,0,0,0.5)"
  ),
  length = list(
    type = "line",
    width = 1,
    value = "Sepal.Length"
  ),
  length.h = list(
    type = "histogram",
    value = "Sepal.Width",
    base = 3
  )  
), height = 300)
```


```{r}
tradingview(aapl, list(
    chart = list(
      decimals = 2
    ),
    close = list(
      type = "line",
      value = "close"
    )
), height = 400)
```

```{r}
tradingview(aapl, list(
    chart = list(
      decimals = 2,
      margins = list(
        top = 0,
        bottom = 0.2
      )
    ),
    candles = list(
      type = "candles"
    ),
    line = list(
      type = "line",
      color = "rgba(255,0,0,0.2)",
      value = "close"
    ),
    volume = list(
      type = "histogram",
      value = "volume",
      color = "rgba(0,0,0,0.2)",
      overlay = TRUE,
      margins = list(
        top = 0.8,
        bottom = 0
      )
    )
), height = 400)
```
```{r}
tv_add <- function(., name, value) {
  .$x$settings[[name]] = value
  .
}

margins <- function(top = 0, bottom = 0) {
  list(top = top, bottom = bottom)
}

addLine <- function(., name = "line", width = 1, value = "value", color = "red", overlay = FALSE) {
  tv_add(., name, list(type = "line", width = width, value = value, color = color, overlay = overlay))
}

addChart <- function(., decimals = 5, margins = margins(0, 0)) {
  tv_add(., name = "chart", value = list(decimals = decimals, margins = margins))
}

addCandles <- function(., name = "candles", value = "value", open = "open", close = "close", high = "high", low = "low", time = "time") {
  tv_add(., name, list(type = "candles", open = open, close = close, high = high, low = low, time = time))
}

tradingview(data) %>% 
  addChart(decimals = 2, margins = margins(0,0)) %>%
  addLine(name = "width", overlay = TRUE, width = 1, value = "Sepal.Width", color = "rgba(255,0,0,0.5)") %>%
  addLine(name = "length", width = 1, value = "Sepal.Length", color = "rgba(0,255,0,0.5)")
```

```{r}
tradingview(appl) %>% 
  addChart(decimals = 2, margins = margins(0,0)) %>%
  addCandles()
```

